name: push-geojson
on:
  push:
    branches:
      - dev
jobs:
  push-geojson-online:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'dev'
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}
    - name: Push remote
      run: |
        cd && scp -P 27 -i /home/runner/.ssh/id_rsa /home/runner/work/pifm/pifm/buildings.json ${{ secrets.SSH_TARGET }}:/home/ntnlvca/public_html/faubourg